STATUS_SUCCESS = 'success'
STATUS_ERROR = 'error'

DEVICE_OWNER_NETWORK_PREFIX = "network:"
DEVICE_OWNER_P4 = DEVICE_OWNER_NETWORK_PREFIX + "p4"

MODULE_STATE_CREATED = "CREATED"
MODULE_STATE_ATTACHED = "ATTACHED"
